#!/bin/bash -login
 
#PBS -l walltime=2:00:00
#PBS -l nodes=1:ppn=20
#PBS -l mem=16gb
#PBS -M moskovts@msu.edu
#PBS -m abe

source /mnt/home/moskovts/config_modules
source /mnt/home/moskovts/hoomd_env/bin/activate
 
### change to the working directory where your code is located
cd /mnt/home/moskovts/MD


### call your executable
python plotDiff_pG_parallel.py diff_data_new/a40x40_A0.5_yclmb_scatter_thermal_vsG135-155_1.7anneal --NP 19
